[profile.default]
src = "contracts"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "cancun"

[fmt]
line_length = 110
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"

[fuzz]
runs = 512

[invariant]
runs = 128
depth = 64
fail_on_revert = false
show_metrics = true
